CC = g++
CFLAGS = -Wall

all: words_between_two_words

words_between_two_words: words_between_two_words.o
	$(CC) -o words_between_two_words words_between_two_words.o  $(CFLAGS)

clean:	
	rm -f *.o words_between_two_words