CC = g++
CFLAGS = -Wall

all: largest_prime_factor

largest_prime_factor: largest_prime_factor.o
	$(CC) -o largest_prime_factor largest_prime_factor.o  $(CFLAGS)

clean:	
	rm -f *.o largest_prime_factor